spring:
  datasource:
    url: jdbc:sql://${PROD_DB_HOST}:${PROD_DB-PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-holamundoapi

    sql:
      init:
        mode: always